package picante.data.list;

import static com.google.common.base.Preconditions.checkElementIndex;

/**
 * A layer of abstraction to manage the {@link IndexOutOfBoundsException} generated by the retrieval
 * method in the {@link Retrievable} interface.
 * <p>
 * This class will manage the generation of index out of bounds exceptions, blocking access to
 * invoking the {@link AbstractRetrievableWithExceptions#obtain(int, Object)} method if the supplied
 * index lies outside the range allowed by the {@link AbstractRetrievableWithExceptions#size()}
 * method. It is simply a convenience class allowing a user to skip implementing the necessary error
 * handling code on their own.
 * </p>
 * 
 * @param <R>
 */
public abstract class AbstractRetrievableWithExceptions<R> implements Retrievable<R> {

  @Override
  public R get(int index, R buffer) {
    checkElementIndex(index, size());
    return obtain(index, buffer);
  }

  /**
   * Method to actually retrieve the record associated with a particular index. This is used
   * directly in the implementation of {@link AbstractGaugedRetrievableWithExceptions#get(int)} to
   * retrieve the record.
   * 
   * @param index the index of interest
   * @param buffer the mutable buffer to receive the resultant record
   * 
   * @return a reference to buffer for convenience
   */
  protected abstract R obtain(int index, R buffer);

}
