package picante.data.list;

/**
 * A layer of abstraction to manage the {@link IndexOutOfBoundsException} generated by the record
 * retrieval routines in the record table interface.
 * <p>
 * This class will manage the generation of index out of bounds exceptions, blocking access to
 * invoking the {@link AbstractFixedLengthGaugedRetrievableWithExceptions#obtainRecord(int, Object)}
 * or {@link AbstractFixedLengthGaugedRetrievableWithExceptions#obtainTime(int)} methods if the
 * supplied index lies outside the specified range. It is simply a convenience class, if you do not
 * wish to manage the error handling in your own code.
 * </p>
 * 
 * @param <R> the type of the data record required by the implementation
 */
public abstract class AbstractFixedLengthGaugedRetrievableWithExceptions<R>
    extends AbstractGaugedRetrievable<R> {

  protected final int length;

  public AbstractFixedLengthGaugedRetrievableWithExceptions(int length) {
    this.length = length;

    if (length <= 0) {
      throw new IllegalArgumentException(
          "Length: " + length + " is invalid.  Length must be strictly positive.");
    }

  }

  @Override
  public double getGauge(int index) {

    if ((index < 0) || (index > (length - 1))) {
      throw new IndexOutOfBoundsException("The requested record index: " + index
          + " is invalid.  Indices must lie in [0," + (length - 1));
    }

    return obtainTime(index);
  }

  /**
   * Method to actually retrieve the time associated with a particular index. This is used directly
   * in the implementation of
   * {@link AbstractFixedLengthGaugedRetrievableWithExceptions#getGauge(int)} to actually read the
   * record.
   * 
   * @param index index of interest
   * 
   * @return the double capturing the associated time
   */
  protected abstract double obtainTime(int index);

  @Override
  public int size() {
    return length;
  }

  @Override
  public R get(int index, R buffer) {

    if ((index < 0) || (index > (length - 1))) {
      throw new IndexOutOfBoundsException("The requested record index: " + index
          + " is invalid.  Indices must lie in [0," + (length - 1));
    }

    return obtainRecord(index, buffer);
  }

  /**
   * Method to actually retrieve the record associated with a particular index. This is used
   * directly in the implementation of
   * {@link AbstractFixedLengthGaugedRetrievableWithExceptions#get(int, Object)} to retrieve the
   * record.
   * 
   * @param index index of interest
   * @param buffer buffer to receive the record
   * 
   * @return reference to buffer for convenience
   */
  protected abstract R obtainRecord(int index, R buffer);

}
