/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package picante.spice.kernelpool.parser.time;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 1;
  /** RegularExpression Id. */
  int QUOTED_YEAR = 2;
  /** RegularExpression Id. */
  int YEAR = 3;
  /** RegularExpression Id. */
  int UNSIGNED_INTEGER = 4;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int BLANK = 6;
  /** RegularExpression Id. */
  int WHITESPACE = 7;
  /** RegularExpression Id. */
  int COMMA = 8;
  /** RegularExpression Id. */
  int TWOCOMMA = 9;
  /** RegularExpression Id. */
  int JD = 10;
  /** RegularExpression Id. */
  int ISOT = 11;
  /** RegularExpression Id. */
  int AD = 12;
  /** RegularExpression Id. */
  int BC = 13;
  /** RegularExpression Id. */
  int MON = 14;
  /** RegularExpression Id. */
  int TUE = 15;
  /** RegularExpression Id. */
  int WED = 16;
  /** RegularExpression Id. */
  int THU = 17;
  /** RegularExpression Id. */
  int FRI = 18;
  /** RegularExpression Id. */
  int SAT = 19;
  /** RegularExpression Id. */
  int SUN = 20;
  /** RegularExpression Id. */
  int JAN = 21;
  /** RegularExpression Id. */
  int FEB = 22;
  /** RegularExpression Id. */
  int MAR = 23;
  /** RegularExpression Id. */
  int APR = 24;
  /** RegularExpression Id. */
  int MAY = 25;
  /** RegularExpression Id. */
  int JUN = 26;
  /** RegularExpression Id. */
  int JUL = 27;
  /** RegularExpression Id. */
  int AUG = 28;
  /** RegularExpression Id. */
  int SEP = 29;
  /** RegularExpression Id. */
  int OCT = 30;
  /** RegularExpression Id. */
  int NOV = 31;
  /** RegularExpression Id. */
  int DEC = 32;
  /** RegularExpression Id. */
  int YEARAD = 33;
  /** RegularExpression Id. */
  int YEARBC = 34;
  /** RegularExpression Id. */
  int DASH = 35;
  /** RegularExpression Id. */
  int COLON = 36;
  /** RegularExpression Id. */
  int PERIOD = 37;
  /** RegularExpression Id. */
  int DAYOFYEAR = 38;
  /** RegularExpression Id. */
  int SLASH = 39;
  /** RegularExpression Id. */
  int QUOTE = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NUMBER>",
    "<QUOTED_YEAR>",
    "<YEAR>",
    "<UNSIGNED_INTEGER>",
    "<DIGIT>",
    "<BLANK>",
    "<WHITESPACE>",
    "\",\"",
    "<TWOCOMMA>",
    "\"JD\"",
    "\"T\"",
    "<AD>",
    "<BC>",
    "<MON>",
    "<TUE>",
    "<WED>",
    "<THU>",
    "<FRI>",
    "<SAT>",
    "<SUN>",
    "<JAN>",
    "<FEB>",
    "<MAR>",
    "<APR>",
    "\"MAY\"",
    "<JUN>",
    "<JUL>",
    "<AUG>",
    "<SEP>",
    "<OCT>",
    "<NOV>",
    "<DEC>",
    "<YEARAD>",
    "<YEARBC>",
    "\"-\"",
    "\":\"",
    "\".\"",
    "<DAYOFYEAR>",
    "\"/\"",
    "\"\\\'\"",
  };

}
