package picante.exceptions;

/**
 * Parent of all exceptions generated by the picante library.
 */
public class PicanteException extends Exception {

  /**
   * Default serial version UID.
   */
  private static final long serialVersionUID = 1L;

  public PicanteException() {}

  public PicanteException(String message) {
    super(message);
  }

  public PicanteException(Throwable cause) {
    super(cause);
  }

  public PicanteException(String message, Throwable cause) {
    super(message, cause);
  }

}
