/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package picante.spice.kernelpool.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 3;
  /** RegularExpression Id. */
  int EOL = 4;
  /** RegularExpression Id. */
  int LONE_BEGINTEXT = 7;
  /** RegularExpression Id. */
  int KEYWORD_PLUS_EQUALS = 8;
  /** RegularExpression Id. */
  int KEYWORD = 9;
  /** RegularExpression Id. */
  int KEYWORD_CHAR = 10;
  /** RegularExpression Id. */
  int EQUALS = 11;
  /** RegularExpression Id. */
  int PLUS_EQUALS = 12;
  /** RegularExpression Id. */
  int DATE = 14;
  /** RegularExpression Id. */
  int NUMBER = 15;
  /** RegularExpression Id. */
  int EXPONENT = 16;
  /** RegularExpression Id. */
  int LEFT_PAREN = 18;
  /** RegularExpression Id. */
  int NEWLINE = 19;
  /** RegularExpression Id. */
  int QUOTED_STRING = 21;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 22;
  /** RegularExpression Id. */
  int LIST_DATE = 24;
  /** RegularExpression Id. */
  int LIST_NUMBER = 25;
  /** RegularExpression Id. */
  int LIST_QUOTED_STRING = 28;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int KEYWORD_STATE = 1;
  /** Lexical state. */
  int VALUE_STATE = 2;
  /** Lexical state. */
  int VALUE_STRING = 3;
  /** Lexical state. */
  int LIST_STATE = 4;
  /** Lexical state. */
  int LIST_STRING = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<WHITESPACE>",
    "<EOL>",
    "<token of kind 5>",
    "<token of kind 6>",
    "<LONE_BEGINTEXT>",
    "<KEYWORD_PLUS_EQUALS>",
    "<KEYWORD>",
    "<KEYWORD_CHAR>",
    "\"=\"",
    "\"+=\"",
    "<token of kind 13>",
    "<DATE>",
    "<NUMBER>",
    "<EXPONENT>",
    "\"\\\'\"",
    "\"(\"",
    "<NEWLINE>",
    "<token of kind 20>",
    "\"\\\'\"",
    "\")\"",
    "<token of kind 23>",
    "<LIST_DATE>",
    "<LIST_NUMBER>",
    "\"\\\'\"",
    "<token of kind 27>",
    "\"\\\'\"",
  };

}
